WebMvc.Web/Areas/Admin/Controllers/SettingController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Web.Mvc;
using WebMvc.Domain.Constants;
using WebMvc.Domain.Interfaces.Services;
using WebMvc.Domain.Interfaces.UnitOfWork;
using WebMvc.Web.Application;
using WebMvc.Web.Areas.Admin.ViewModels;

namespace WebMvc.Web.Areas.Admin.Controllers
{
    [Authorize(Roles = AppConstants.AdminRoleName)]
    public class SettingController : BaseAdminController
    {
        public SettingController(ILoggingService loggingService, IUnitOfWorkManager unitOfWorkManager, IMembershipService membershipService, ISettingsService settingsService, ILocalizationService localizationService)
            : base(loggingService, unitOfWorkManager, membershipService, settingsService, localizationService)
        {

        }

        public ActionResult index()
        {
            return General();
        }

        #region General Setting
        public ActionResult General()
        {
            var model = new AdminGeneralSettingViewModel
            {
                WebsiteName = SettingsService.GetSetting("WebsiteName"),
                WebsiteUrl = SettingsService.GetSetting("WebsiteUrl"),
                PageTitle = SettingsService.GetSetting("PageTitle"),
                MetaDesc = SettingsService.GetSetting("MetaDesc"),
            };

            return View("General", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult General(AdminGeneralSettingViewModel setting)
        {
            if (ModelState.IsValid)
            {
                using (var unitOfWork = UnitOfWorkManager.NewUnitOfWork())
                {
                    try
                    {
                        SettingsService.SetSetting("WebsiteName", setting.WebsiteName);
                        SettingsService.SetSetting("WebsiteUrl", setting.WebsiteUrl);
                        SettingsService.SetSetting("PageTitle", setting.PageTitle);
                        SettingsService.SetSetting("MetaDesc", setting.MetaDesc);


                        unitOfWork.Commit();
                        TempData[AppConstants.MessageViewBagName] = new GenericMessageViewModel
                        {
                            Message = LocalizationService.GetResourceString("Cập nhật thành công!"),
                            MessageType = GenericMessages.success
                        };
                    }
                    catch (Exception ex)
                    {
                        unitOfWork.Rollback();
                        LoggingService.Error(ex);
                    }
                }

            }



            return View("General", setting);
        }

        #endregion General Setting

        #region company information
        public ActionResult Business()
        {
            var model = new AdminBusinessSettingViewModel 
            {
                BusinessName = SettingsService.GetSetting("BusinessName"),
                Introduce = SettingsService.GetSetting("Introduce"),
                Greeting = SettingsService.GetSetting("Greeting"),

                Fanpage = SettingsService.GetSetting("Fanpage"),
                Hotline = SettingsService.GetSetting("Hotline"),
                HotlineImg = SettingsService.GetSetting("HotlineImg"),
                Addrens = new List<AdminShowroomSettingViewModel>(),

                BankID = SettingsService.GetSetting("BankID"),
                BankName = SettingsService.GetSetting("BankName"),
                BankUser = SettingsService.GetSetting("BankUser"),
            };

            var ShowroomCount = SettingsService.GetSetting("ShowroomCount");
            int count = 0;
            try
            {
                count = int.Parse(ShowroomCount);
            }
            catch { }

            for(int i = 0; i < count; i++)
            {
                model.Addrens.Add(new AdminShowroomSettingViewModel {
                   Addren = SettingsService.GetSetting("Showroom["+i+"].Address"),
                   iFrameMap = SettingsService.GetSetting("Showroom[" + i + "].iFrameMap"),
                });
            }

            return View( model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Business(AdminBusinessSettingViewModel setting)
        {
            if (ModelState.IsValid)
            {
                using (var unitOfWork = UnitOfWorkManager.NewUnitOfWork())
                {
                    try
                    {
                        SettingsService.SetSetting("BusinessName", setting.BusinessName);
                        SettingsService.SetSetting("Introduce", setting.Introduce);
                        SettingsService.SetSetting("Greeting", setting.Greeting);
                        SettingsService.SetSetting("Fanpage", setting.Fanpage);
                        SettingsService.SetSetting("Hotline", setting.Hotline);
                        SettingsService.SetSetting("HotlineImg", setting.HotlineImg);

                        SettingsService.SetSetting("BankID", setting.BankID);
                        SettingsService.SetSetting("BankName", setting.BankName);
                        SettingsService.SetSetting("BankUser", setting.BankUser);

                        if (setting.Addrens != null)
                        {
                            int count = setting.Addrens.Count;
                            SettingsService.SetSetting("ShowroomCount", count.ToString());

                            for (int i = 0; i < count; i++)
                            {
                                SettingsService.SetSetting("Showroom[" + i + "].Address", setting.Addrens[i].Addren);
                                SettingsService.SetSetting("Showroom[" + i + "].iFrameMap", setting.Addrens[i].iFrameMap);
                            }
                        }
                        else
                        {
                            SettingsService.SetSetting("ShowroomCount", "0");
                            setting.Addrens = new List<AdminShowroomSettingViewModel>();
                        }
                        

                        unitOfWork.Commit();
                        TempData[AppConstants.MessageViewBagName] = new GenericMessageViewModel
                        {
                            Message = LocalizationService.GetResourceString("Cập nhật thành công!"),
                            MessageType = GenericMessages.success
                        };
                    }
                    catch (Exception ex)
                    {
                        unitOfWork.Rollback();
                        LoggingService.Error(ex);
                    }
                }

            }



            return View(setting);
        }
        #endregion

        #region TermsConditions Setting
        public ActionResult TermsConditions()
        {

            return View();
        }
        #endregion TermsConditions Setting

        #region Email Setting
        public ActionResult Email()
        {

            return View();
        }
        #endregion Email Setting

        #region Registration Setting
        public ActionResult Registration()
        {

            return View();
        }
        #endregion Registration Setting

        #region Language Setting
        public ActionResult Language()
        {
            var model = new AdminLanguageSettingViewModel
            {
                LanguageDefault = LocalizationService.DefaultLanguage.Id,
                AllLanguage = LocalizationService.GetBaseSelectListLanguages(LocalizationService.GetAll())
            };

            return View("Language", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Language(AdminLanguageSettingViewModel setting)
        {
            if (ModelState.IsValid)
            {
                using (var unitOfWork = UnitOfWorkManager.NewUnitOfWork())
                {
                    setting.AllLanguage = LocalizationService.GetBaseSelectListLanguages(LocalizationService.GetAll());

                    try
                    {
                        SettingsService.SetSetting("LanguageDefault", setting.LanguageDefault.ToString());


                        unitOfWork.Commit();
                    }
                    catch (Exception ex)
                    {
                        unitOfWork.Rollback();
                        LoggingService.Error(ex);
                    }
                }

            }



            return View("Language", setting);
        }
        #endregion

        #region Themes Setting
        public ActionResult Themes()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Themes(string activetheme,string atv)
        {
            if (ModelState.IsValid)
            {
                using (var unitOfWork = UnitOfWorkManager.NewUnitOfWork())
                {
                    try
                    {
                        if(atv == "Deaactive")
                        {
                            SettingsService.SetSetting("Theme", "");
                        }
                        else
                        {
                            SettingsService.SetSetting("Theme", activetheme);
                        }

                        unitOfWork.Commit();
                    }
                    catch (Exception ex)
                    {
                        unitOfWork.Rollback();
                        LoggingService.Error(ex);
                    }
                }

            }

            return View();
        }

        public ActionResult ThemeConfig(string id)
        {
            ViewBag.id = id;
            ViewBag.json = ThemesSetting.getSettingTheme(id);
            return View();
        }

        [HttpPost]
        [ActionName("ThemeConfig")]

WebMvc.Web/Areas/Admin/Views/Setting/Business.cshtml
@model WebMvc.Web.Areas.Admin.ViewModels.AdminBusinessSettingViewModel

@{
    ViewBag.Title = "Thông tin doanh nghiệp";
}

@using (Html.BeginForm("Business", "Setting", FormMethod.Post))
{
    @Html.ValidationSummary(false)
    @Html.AntiForgeryToken()

    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title">@ViewBag.Title</h4>
        </div>
        <div class="panel-collapse">
            <div class="panel-body">
                <div class="form-group">
                    @Html.LabelFor(model => model.BusinessName)
                    @Html.TextBoxFor(model => model.BusinessName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.BusinessName)
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Introduce)
                    @Html.TextAreaFor(model => model.Introduce, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Introduce)
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Greeting)
                    @Html.TextAreaFor(model => model.Greeting, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Greeting)
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Hotline)
                    @Html.TextBoxFor(model => model.Hotline, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Hotline)
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.HotlineImg)
                    @Html.TextBoxFor(model => model.HotlineImg, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.HotlineImg)
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Fanpage)
                    @Html.TextBoxFor(model => model.Fanpage, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Fanpage)
                </div>
                <hr />
                <div id="ShowroomList">
                    @for (int i = 0; i < Model.Addrens.Count; i++)
                    {
                        var it = Model.Addrens[i];
                        <div id="Showroom_container_@i">
                            <div class="form-group">
                                <label for="Showroom_@i">Địa chỉ Showroom(@(i + 1))</label>
                                <input class="form-control" id="Showroom_@i" name="Addrens[@i].Addren" type="text" value="@it.Addren" />
                            </div>
                            <div class="form-group">
                                <label for="Showroom_Map_@i">Google Map Showroom(@(i + 1))</label>
                                <input class="form-control" id="Showroom_Map_@i" name="Addrens[@i].iFrameMap" type="text" value="@it.iFrameMap" />
                            </div>
                        </div>
                    }
                </div>
                <script>
                    SHOWROOM.Count = @Model.Addrens.Count ;
                </script>
                <div style="text-align:right;width:100%;">
                    <button type="button" onclick="SHOWROOM.Repmove();" id="repbutton" class="btn btn-danger@(Model.Addrens.Count>0?"":" hidden")">Xóa Showroom</button>
                    <button type="button" onclick="SHOWROOM.Add();" class="btn btn-primary">Thêm Showroom</button>
                </div>
                <hr />
                <div class="form-group">
                    @Html.LabelFor(model => model.BankID)
                    @Html.TextBoxFor(model => model.BankID, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.BankID)
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.BankUser)
                    @Html.TextBoxFor(model => model.BankUser, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.BankUser)
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.BankName)
                    @Html.TextBoxFor(model => model.BankName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.BankName)
                </div>
            </div>
        </div>
    </div>

    <div class="submit-holder">
        <button type="submit" class="btn-mvc-green btn-mvc-large">Save Settings</button>
    </div>
}

WebMvc.Web/Areas/Admin/Views/Setting/CustomCode.cshtml
@model WebMvc.Web.Areas.Admin.ViewModels.CustomCodeViewModels
@{
    ViewBag.Title = "Custom Code";
}
<div class="panel">
    <div class="panel-heading">
        <h4 class="panel-title">
            @ViewBag.Title
        </h4>
    </div>
    <div class="panel-body">
        <p>You can add any custom code (JavaScript, Html and CSS only) to the header and footer of your site using the boxes below.</p>
        <p>Header code will appear just before the closing head tag, and footer code will appear just before the closing body tag. The code will appear on everypage of the forum, so you can use this for things like Analytics.</p>
        @using (Html.BeginForm())
        {
            @Html.ValidationSummary(false)


            <div class="form-group">
                @Html.LabelFor(m => m.CustomHeaderCode)
                @Html.TextAreaFor(m => m.CustomHeaderCode, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.CustomHeaderCode)
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.CustomFooterCode)
                @Html.TextAreaFor(m => m.CustomFooterCode, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.CustomFooterCode)
            </div>

            <div class="submit-holder">
                <input type="submit" class="btn-mvc-green btn-mvc-large" value="Update" />
            </div>
        }

    </div>
</div>

WebMvc.Web/Areas/Admin/Views/Setting/Email.cshtml
@using WebMvc.Web.Application.ExtensionMethods
@model WebMvc.Web.Areas.Admin.ViewModels.AdminEmailSettingViewModel

@{
    ViewBag.Title = "Email Setting";
}

@using (Html.BeginForm("Email", "Setting", FormMethod.Post))
{
    @Html.ValidationSummary(false)
    @Html.AntiForgeryToken()
    
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title">Email Setting</h4>
        </div>
        <div class="panel-collapse">
            <div class="panel-body">
                
            </div>
        </div>
    </div>

    <div class="submit-holder">
        <button type="submit" class="btn-mvc-green btn-mvc-large">Save Settings</button>
    </div>
}

WebMvc.Web/Areas/Admin/Views/Setting/General.cshtml
@using WebMvc.Web.Application.ExtensionMethods
@model WebMvc.Web.Areas.Admin.ViewModels.AdminGeneralSettingViewModel

@{
    ViewBag.Title = "General Setting";
}

@using (Html.BeginForm("General", "Setting", FormMethod.Post))
{
    @Html.ValidationSummary(false)
    @Html.AntiForgeryToken()
    
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title">General Setting</h4>
        </div>
        <div class="panel-collapse">
            <div class="panel-body">
                <div class="form-group">
                    @Html.LabelFor(model => model.WebsiteName)
                    @Html.TextBoxFor(model => model.WebsiteName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.WebsiteName)
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.WebsiteUrl)
                    @Html.TextBoxFor(model => model.WebsiteUrl, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.WebsiteUrl)
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.PageTitle)
                    @Html.TextBoxFor(model => model.PageTitle, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.PageTitle)
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.MetaDesc)
                    @Html.TextAreaFor(model => model.MetaDesc, new { @class = "form-control", @style = "resize:vertical" })
                    @Html.ValidationMessageFor(model => model.MetaDesc)
                </div>

                <div class="checkbox" >
                    @using (Html.BeginLabelFor(m => m.IsClosed, new { @class = "checkbox" }))
                    {
                        @Html.CheckBoxFor(m => m.IsClosed)
                    }
                    @Html.ValidationMessageFor(m => m.IsClosed)
                </div>

                <div class="checkbox">
                    @using (Html.BeginLabelFor(m => m.DisableStandardRegistration, new { @class = "checkbox" }))
                    {
                        @Html.CheckBoxFor(m => m.DisableStandardRegistration)
                    }
                    <p class="help-block">This disables the standard registration form, perfect for people who just want to use Social logins only</p>
                    @Html.ValidationMessageFor(m => m.DisableStandardRegistration)
                </div>

                <div class="checkbox">
                    @using (Html.BeginLabelFor(m => m.EnableRSSFeeds, new { @class = "checkbox" }))
                    {
                        @Html.CheckBoxFor(m => m.EnableRSSFeeds)
                    }
                    @Html.ValidationMessageFor(m => m.EnableRSSFeeds)
                </div>
            </div>
        </div>
    </div>

    <div class="submit-holder">
        <button type="submit" class="btn-mvc-green btn-mvc-large">Save Settings</button>
    </div>
}

WebMvc.Web/Areas/Admin/Views/Setting/Language.cshtml
@using WebMvc.Web.Application.ExtensionMethods
@model WebMvc.Web.Areas.Admin.ViewModels.AdminLanguageSettingViewModel

@{
    ViewBag.Title = "Language Setting";
}

@using (Html.BeginForm("Language", "Setting", FormMethod.Post))
{
    @Html.ValidationSummary(false)
    @Html.AntiForgeryToken()
    
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title">Language Setting</h4>
        </div>
        <div class="panel-collapse">
            <div class="panel-body">
                <div class="form-group">
                    @Html.LabelFor(model => model.LanguageDefault)
                    @Html.DropDownListFor(model => model.LanguageDefault, Model.AllLanguage, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.LanguageDefault)
                </div>
            </div>
        </div>
    </div>

    <div class="submit-holder">
        <button type="submit" class="btn-mvc-green btn-mvc-large">Save Settings</button>
    </div>
}

WebMvc.Web/Areas/Admin/Views/Setting/Registration.cshtml
@using WebMvc.Web.Application.ExtensionMethods
@model WebMvc.Web.Areas.Admin.ViewModels.AdminRegistrationSettingViewModel

@{
    ViewBag.Title = "Registration Setting";
}

@using (Html.BeginForm("Registration", "Setting", FormMethod.Post))
{
    @Html.ValidationSummary(false)
    @Html.AntiForgeryToken()
    
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title">Registration Setting</h4>
        </div>
        <div class="panel-collapse">
            <div class="panel-body">
                
            </div>
        </div>
    </div>

    <div class="submit-holder">
        <button type="submit" class="btn-mvc-green btn-mvc-large">Save Settings</button>
    </div>
}

WebMvc.Web/Areas/Admin/Views/Setting/TermsConditions.cshtml
@using WebMvc.Web.Application.ExtensionMethods
@model WebMvc.Web.Areas.Admin.ViewModels.AdminTermsConditionsSettingViewModel

@{
    ViewBag.Title = "Terms & Conditions Setting";
}

@using (Html.BeginForm("TermsConditions", "Setting", FormMethod.Post))
{
    @Html.ValidationSummary(false)
    @Html.AntiForgeryToken()
    
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title">Terms & Conditions Setting</h4>
        </div>
        <div class="panel-collapse">
            <div class="panel-body">
                
            </div>
        </div>
    </div>

    <div class="submit-holder">
        <button type="submit" class="btn-mvc-green btn-mvc-large">Save Settings</button>
    </div>
}

WebMvc.Web/Areas/Admin/Views/Setting/ThemeConfig.cshtml
@using WebMvc.Domain.Interfaces.Services
@{
    ViewBag.Title = "Theme config";

    var _menuService = DependencyResolver.Current.GetService<IMenuService>();
    var _categoryService = DependencyResolver.Current.GetService<ICategoryService>();
}
@using (Html.BeginForm("ThemeConfig", "Setting", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="panel">
        <div class="panel-heading">
            <h5>@ViewBag.id config</h5>
        </div>
        <div class="panel-content">
            @foreach (var item in ViewBag.json)
            {
            <div class="form-group">
                @switch ((string)item.Value.Type)
                {
                    case "MenuID":
                        <label for="@item.Name">@item.Value.LabelName</label>
                        <select class="form-control" id="@item.Name" name="@item.Name">
                            <option value="">--No Select--</option>
                            @foreach (var it in _menuService.GetAll().ToList())
                            {
                                <option value="@it.Id" @((it.Id.ToString() == (string)item.Value.Value) ? "selected=\"selected\"" : "")>@it.Name</option>
                            }
                        </select>
                        break;
                    case "CategoryID":
                        <label for="@item.Name">@item.Value.LabelName</label>
                        <select class="form-control" id="@item.Name" name="@item.Name">
                            <option value="">--No Select--</option>
                            @foreach (var it in _categoryService.GetAll().ToList())
                            {
                                <option value="@it.Id" @((it.Id.ToString() == (string)item.Value.Value) ? "selected=\"selected\"" : "")>@it.Name</option>
                            }
                        </select>
                        break;
                    case "NewsID":
                        Topic news = null;
                        string title = "";
                        if (item.Value.Value != null && item.Value.Value != "")
                        {
                            news = AppHelpers.GetTopic(new Guid((string)item.Value.Value));
                            if (news != null)
                            {
                                title = news.Name;
                            }

                        }

                        <label for="@item.Name">@item.Value.LabelName</label>
                        <div style="display:table;width:100%">
                            <input id="@(item.Name)_title" value="@title" class="form-control" style="float:left; width: calc(100% - 100px)" readonly="readonly" />
                            <input type="hidden" id="@item.Name" name="@item.Name" value="@item.Value.Value" />
                            <button type="button" onclick="popupSelectNews('@item.Name','@(item.Name)_title')" class="btn btn-default" style="width:90px;float:right">Chọn</button>
                        </div>
                        break;
                    case "ProductID":
                        Product prod = null;
                        string titlep = "";
                        if (item.Value.Value != null && item.Value.Value != "")
                        {
                            prod = AppHelpers.GetProduct(new Guid((string)item.Value.Value));
                            if (prod != null)
                            {
                                titlep = prod.Name;
                            }
                        }

                        <label for="@item.Name">@item.Value.LabelName</label>
                        <div style="display:table;width:100%">
                            <input id="@(item.Name)_title" value="@titlep" class="form-control" style="float:left; width: calc(100% - 100px)" readonly="readonly" />
                            <input type="hidden" id="@item.Name" name="@item.Name" value="@item.Value.Value" />
                            <button type="button" onclick="popupSelectProduct('@item.Name','@(item.Name)_title')" class="btn btn-default" style="width:90px;float:right">Chọn</button>
                        </div>
                        break;
                    case "ListProductClass":
                        int i = 0;
                        <label>@item.Value.LabelName</label>
                        <table class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>Tên nhóm sản phẩm</th>
                                    <th>Chọn</th>
                                </tr>
                            </thead>
                            <tbody id="Container@(item.Name)">
                                @if (item.Value.Value != null)
                                {
                                    foreach (var it in item.Value.Value)
                                    {
                                        string titlep1 = "";
                                        if (it != null && (string)it != "")
                                        {
                                            titlep1 = AppHelpers.GetNameGroupProduct(new Guid((string)it));
                                        }
                                        <tr id="@(item.Name)_@(++i)">
                                            <td>
                                                <input id="@(item.Name)_@(i)_title" value="@titlep1" class="form-control" readonly="readonly" />
                                                <input type="hidden" id="@(item.Name)_@(i)_id" name="@(item.Name)[@(i)]" value="@it" />
                                            </td>
                                            <td>
                                                <button type="button" onclick="popupSelectGroupProduct('@(item.Name)_@(i)_id','@(item.Name)_@(i)_title')" class="btn btn-default">Chọn</button>
                                            </td>
                                        </tr>
                                    }
                                }

                            </tbody>
                            <tr>
                                <td colspan="2">
                                    <button type="button" onclick="Add@(item.Name)();" class="btn btn-default">Thêm nhóm sản phẩm</button>
                                    <button type="button" onclick="Repmove@(item.Name)();" class="btn btn-default">xóa nhóm sản phẩm</button>
                                </td>
                            </tr>
                        </table>
                        <script>
                            var Num@(item.Name) = @i ;
                            function Add@(item.Name)() {
                                //alert("svs");
                                var iTr = document.createElement('tr');
                                iTr.id = "@(item.Name)_" + (++Num@(item.Name)) ;

                                var html = "<td>";
                                html += "<input id=\"@(item.Name)_"+ Num@(item.Name) +"_title\" class=\"form-control\" readonly=\"readonly\" />";
                                html += "<input type=\"hidden\" id=\"@(item.Name)_"+ Num@(item.Name) +"_id\" name=\"@(item.Name)["+ Num@(item.Name) +"]\" />";
                                html += "</td>";
                                html += "<td>";
                                html += "<button type=\"button\" onclick=\"popupSelectGroupProduct('@(item.Name)_"+ Num@(item.Name) +"_id','@(item.Name)_"+ Num@(item.Name) +"_title')\" class=\"btn btn-default\">Chọn</button>";
                                html += "</td>";

                                iTr.innerHTML = html;

                                var sList = document.getElementById("Container@(item.Name)");
                                sList.appendChild(iTr);
                            }

                            function Repmove@(item.Name)() {
                                if (Num@(item.Name) > 0) {
                                    $("#@(item.Name)_" + (Num@(item.Name)--)).remove();
                                }
                            }
                        </script>
                        break;
                }



            </div>
            }

            <div class="submit-holder">
                <button type="submit" class="btn-mvc-green btn-mvc-large">Save Config</button>
                <a class="btn-mvc-red btn-mvc-large" href="@Url.Action("Themes", "Setting", new { area = "Admin" }, null)">Back</a>
            </div>
        </div>
    </div>
}