WebMvc.Web/Areas/Admin/Controllers/AdminLanguageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using WebMvc.Domain.Constants;
using WebMvc.Domain.DomainModel.Entities;
using WebMvc.Domain.Interfaces.Services;
using WebMvc.Domain.Interfaces.UnitOfWork;
using WebMvc.Utilities;
using WebMvc.Web.Areas.Admin.ViewModels;
using static WebMvc.Web.Areas.Admin.ViewModels.ListLanguagesViewModel;

namespace WebMvc.Web.Areas.Admin.Controllers
{
    [Authorize(Roles = AppConstants.AdminRoleName)]
    public class AdminLanguageController : BaseAdminController
    {
        public AdminLanguageController( ILoggingService loggingService, IUnitOfWorkManager unitOfWorkManager, IMembershipService membershipService, ISettingsService settingsService, ILocalizationService localizationService)
            : base(loggingService, unitOfWorkManager, membershipService, settingsService, localizationService)
        {
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }

        public ActionResult ImportExport()
        {
            return View();
        }

        /// <summary>
        /// Manage resource keys (for all languages)
        /// </summary>
        /// <returns></returns>
        public ActionResult ManageResourceKeys(int? p, string search)
        {
            try
            {
                using (UnitOfWorkManager.NewUnitOfWork())
                {
                    if (!ModelState.IsValid)
                    {
                        var errors = (from key in ModelState.Keys select ModelState[key] into state where state.Errors.Any() select state.Errors.First().ErrorMessage).ToList();
                        ShowErrors(errors);
                    }

                    return ListResourceKeys(p, search);
                }
            }
            catch (Exception ex)
            {
                ShowError(ex.Message);
                return RedirectToAction("Index");
            }
        }

        /// <summary>
        /// Get - create a new language
        /// </summary>
        /// <returns></returns>
        [ChildActionOnly]
        public PartialViewResult CreateLanguage()
        {
            return PartialView();
        }

        /// <summary>
        /// Post - create a new language
        /// </summary>
        /// <param name="languageViewModel"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = AppConstants.AdminRoleName)]
        public ActionResult CreateLanguage(CreateLanguageViewModel languageViewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    // Get the culture info
                    var cultureInfo = LanguageUtils.GetCulture(languageViewModel.Name);

                    using (var unitOfWork = UnitOfWorkManager.NewUnitOfWork())
                    {
                        try
                        {
                            LocalizationService.Add(cultureInfo);
                            unitOfWork.Commit();
                            ShowSuccess("Language Created");
                        }
                        catch (Exception ex)
                        {
                            unitOfWork.Rollback();
                            LoggingService.Error(ex);
                            throw;
                        }
                    }
                }
                else
                {

                    var errors = (from key in ModelState.Keys select ModelState[key] into state where state.Errors.Any() select state.Errors.First().ErrorMessage).ToList();
                    ShowErrors(errors);
                }
            }
            catch (Exception ex)
            {
                ShowError(ex.Message);
            }

            // Default ie error
            return RedirectToAction("Index");
        }

        public ActionResult AddResourceKey()
        {
            var viewModel = new LocaleResourceKeyViewModel();

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddResourceKey(LocaleResourceKeyViewModel newResourceKeyViewModel)
        {
            using (var unitOfWork = UnitOfWorkManager.NewUnitOfWork())
            {
                try
                {
                    var resourceKeyToSave = new LocaleResourceKey
                    {
                        Name = newResourceKeyViewModel.Name,
                        Notes = newResourceKeyViewModel.Notes
                    };

                    LocalizationService.Add(resourceKeyToSave);
                    unitOfWork.Commit();
                    ShowSuccess("Resource key created successfully");
                    var currentLanguage = SettingsService.GetSetting("DefaultLanguage");
                    return RedirectToAction("ManageLanguageResourceValues", new { languageId = currentLanguage });
                }
                catch (Exception ex)
                {
                    unitOfWork.Rollback();
                    ShowError(ex.Message);
                    LoggingService.Error(ex);
                    return RedirectToAction("AddResourceKey");
                }
            }
        }

        [HttpPost]
        public void UpdateResourceValue(AjaxEditLanguageValueViewModel viewModel)
        {
            if (Request.IsAjaxRequest())
            {
                using (var unitOfWork = UnitOfWorkManager.NewUnitOfWork())
                {
                    try
                    {
                        LocalizationService.UpdateResourceString(viewModel.LanguageId, viewModel.ResourceKey,
                                                                 viewModel.NewValue);
                        unitOfWork.Commit();
                    }
                    catch (Exception ex)
                    {
                        unitOfWork.Rollback();
                        LoggingService.Error(ex);
                    }
                }
            }
        }

        /// <summary>
        /// Returns a partial view listing all languages
        /// </summary>
        /// <returns></returns>
        [ChildActionOnly]
        public PartialViewResult GetLanguages()
        {
            using (UnitOfWorkManager.NewUnitOfWork())
            {
                var viewModel = new ListLanguagesViewModel { Languages = new List<LanguageDisplayViewModel>() };

                try
                {
                    foreach (var language in LocalizationService.GetAll())
                    {
                        var languageViewModel = new LanguageDisplayViewModel
                        {
                            Id = language.Id,
                            IsDefault = language.Id == LocalizationService.CurrentLanguage.Id,
                            Name = language.Name,
                            LanguageCulture = language.LanguageCulture,
                        };

                        viewModel.Languages.Add(languageViewModel);

                    }
                }
                catch (Exception ex)
                {
                    ShowError(ex.Message);
                    LoggingService.Error(ex);
                }

                return PartialView(viewModel);
            }
        }

        public ActionResult ManageLanguageResourceValues(Guid languageId, int? p, string search)
        {
            return GetLanguageResources(false, languageId, p, search);
        }

        #region Private
        private ActionResult GetLanguageResources(bool searchByKey, Guid languageId, int? p, string search)
        {
            try
            {
                using (UnitOfWorkManager.NewUnitOfWork())
                {
                    var language = LocalizationService.Get(languageId);

                    int count = LocalizationService.GetCountResourceKey();
                    int limit = 30;
                    int MaxPage = count / limit;
                    if (count % limit > 0) MaxPage++;
                    if (MaxPage == 0) MaxPage = 1;

                    if (p == null) p = 1;
                    if (p > MaxPage) p = MaxPage;

                    var resources = LocalizationService.GetListResourceKey((int)p, limit);

                    var resourceListModel = new LanguageListResourcesViewModel
                    {
                        LanguageId = language.Id,
                        LanguageName = language.Name,
                        LocaleResources = new List<LocaleResourceViewModel>(),
                        PageIndex = p,
                        TotalCount = count,
                        Search = search,
                        TotalPages = MaxPage
                    };

                    foreach (var it in resources)
                    {
                        var ResourceString = LocalizationService.GetValueResource(it.Id, languageId);

                        if (ResourceString == null) ResourceString = new LocaleStringResource {
                            ResourceValue = ""
                        };

                        resourceListModel.LocaleResources.Add(new LocaleResourceViewModel {
                            Id = ResourceString.Id,
                            ResourceKeyId = it.Id,
                            LocaleResourceKey = it.Name,
                            ResourceValue = ResourceString.ResourceValue
                        });
                    }



                    return View("ListValues", resourceListModel);

                }
            }
            catch (Exception ex)
            {
                ShowError(ex.Message);
            }

            // Default ie error
            return RedirectToAction("Index");
        }

        /// <summary>

WebMvc.Web/Areas/Admin/Controllers/ImportExportController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using WebMvc.Domain.Constants;
using WebMvc.Domain.DomainModel.General;
using WebMvc.Domain.Interfaces.Services;
using WebMvc.Domain.Interfaces.UnitOfWork;
using WebMvc.Web.Application.CustomActionResults;
using WebMvc.Web.Areas.Admin.ViewModels;

namespace WebMvc.Web.Areas.Admin.Controllers
{
    public class ImportExportController : BaseAdminController
    {
        public ImportExportController(ILoggingService loggingService, IUnitOfWorkManager unitOfWorkManager, IMembershipService membershipService, ISettingsService settingsService, ILocalizationService localizationService)
            : base(loggingService, unitOfWorkManager, membershipService, settingsService, localizationService)
        {

        }

        // GET: Admin/ImportExport
        public ActionResult Index()
        {
            return View();
        }

        #region Private methods

        /// <summary>
        /// Convert an import report into JSON data
        /// </summary>
        /// <param name="report"></param>
        /// <returns></returns>
        private static object ToJSON(CsvReport report)
        {
            var oSerializer = new JavaScriptSerializer();
            var json = new
            {
                HasErrors = report.Errors.Any(),
                HasWarnings = report.Warnings.Any(),
                Warnings = oSerializer.Serialize(report.Warnings.ExtractMessages()),
                Errors = oSerializer.Serialize(report.Errors.ExtractMessages()),
            };

            return json;
        }


        #endregion

        [ChildActionOnly]
        public PartialViewResult Languages()
        {
            using (UnitOfWorkManager.NewUnitOfWork())
            {
                var importExportViewModel = new LanguagesHomeViewModel();

                // For languages we need a list of export languages and import languages
                var languageImportExportViewModel = new LanguageImportExportViewModel
                {
                    ExportLanguages = LocalizationService.LanguagesInDb,
                    ImportLanguages = LocalizationService.LanguagesAll
                };
                importExportViewModel.LanguageViewModel = languageImportExportViewModel;

                return PartialView(importExportViewModel);
            }
        }

        /// <summary>
        /// Export a language in csv format
        /// </summary>
        /// <param name="languageCulture"></param>
        /// <returns></returns>
        public CsvFileResult ExportLanguage(string languageCulture)
        {
            using (UnitOfWorkManager.NewUnitOfWork())
            {
                var csv = new CsvFileResult();

                var language = LocalizationService.GetLanguageByLanguageCulture(languageCulture);

                if (language != null)
                {
                    csv.FileDownloadName = languageCulture + ".csv";
                    csv.Body = LocalizationService.ToCsv(language);
                }
                else
                {
                    csv.Body = "No such language";
                    LoggingService.Error("No such language when trying to export language");
                }

                return csv;
            }
        }

        /// <summary>
        /// Post of data for language import (file info)
        /// </summary>
        /// <param name="languageCulture">This defines the name etc of the imported language</param>
        /// <param name="file">The name-value pairs for the language content</param>
        /// <returns></returns>
        [HttpPost]
        public WrappedJsonResult ImportLanguage(string languageCulture, HttpPostedFileBase file)
        {
            using (var unitOfWork = UnitOfWorkManager.NewUnitOfWork())
            {
                var report = new CsvReport();

                //http://www.dustinhorne.com/post/2011/11/16/AJAX-File-Uploads-with-jQuery-and-MVC-3.aspx
                try
                {
                    // Verify that the user selected a file
                    if (file != null && file.ContentLength > 0)
                    {
                        // Unpack the data
                        var allLines = new List<string>();
                        using (var streamReader = new StreamReader(file.InputStream, System.Text.Encoding.UTF8, true))
                        {
                            while (streamReader.Peek() >= 0)
                            {
                                allLines.Add(streamReader.ReadLine());
                            }
                        }

                        // Read the CSV file and generate a language
                        report = LocalizationService.FromCsv(languageCulture, allLines);
                        unitOfWork.Commit();
                    }
                    else
                    {
                        report.Errors.Add(new CsvErrorWarning
                        {
                            ErrorWarningType = CsvErrorWarningType.BadDataFormat,
                            Message = "File does not contain a language."
                        });
                    }
                }
                catch (Exception ex)
                {
                    unitOfWork.Rollback();
                    report.Errors.Add(new CsvErrorWarning
                    {
                        ErrorWarningType = CsvErrorWarningType.GeneralError,
                        Message = string.Format("Unable to import language: {0}", ex.Message)
                    });
                }

                return new WrappedJsonResult { Data = ToJSON(report) };
            }
        }

    }
}

WebMvc.Web/Areas/Admin/Views/AdminLanguage/AddResourceKey.cshtml
@model WebMvc.Web.Areas.Admin.ViewModels.LocaleResourceKeyViewModel

@{
    ViewBag.Title = "Add Resource Key";
}

@Html.Partial("_LanguageOptions")

<div class="panel">
    <div class="panel-heading">
        <h5>@ViewBag.Title</h5>
    </div>
    <div class="panel-content">
        @using (Html.BeginForm("AddResourceKey", "AdminLanguage", FormMethod.Post))
        {
            @Html.ValidationSummary(false)
            @Html.AntiForgeryToken()

            <div class="form-group">
                @Html.LabelFor(model => model.Name)
                @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Name)
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Notes)
                @Html.TextAreaFor(model => model.Notes, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Notes)
            </div>

            <div class="submit-holder">
                <input type="submit" class="btn-mvc-green btn-mvc-large" value="Create" />
            </div>

        }

    </div>
</div>

WebMvc.Web/Areas/Admin/Views/AdminLanguage/Create.cshtml
@{
    ViewBag.Title = "Create New Language";
}
@Html.Action("CreateLanguage")

WebMvc.Web/Areas/Admin/Views/AdminLanguage/CreateLanguage.cshtml
@using WebMvc.Utilities
@model WebMvc.Web.Areas.Admin.ViewModels.CreateLanguageViewModel

@{
    ViewBag.Title = "Create Language";
}

@Html.Partial("_LanguageOptions")

<div class="panel">
    <div class="panel-heading">
        <h5>@ViewBag.Title</h5>
    </div>
    <div class="panel-content">
        @using (Html.BeginForm("CreateLanguage", "AdminLanguage", FormMethod.Post))
        {
            @Html.ValidationSummary(false)
            @Html.AntiForgeryToken()

            <div class="form-group">
                @Html.LabelFor(model => model.Name)
                @Html.DropDownListFor(model => model.Name, new SelectList(LanguageUtils.AllCultures, "Name", "EnglishName"), new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Name)
            </div>

            <div class="submit-holder">
                <input type="submit" class="btn-mvc-green btn-mvc-large" value="Create" />
            </div>
        }
    </div>
</div>

WebMvc.Web/Areas/Admin/Views/AdminLanguage/GetLanguages.cshtml
@model WebMvc.Web.Areas.Admin.ViewModels.ListLanguagesViewModel

@{
    ViewBag.Title = "All Languages";
}

<div class="panel">
    <div class="panel-heading">
        <h5>@ViewBag.Title</h5>
    </div>
    <div class="panel-content">
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th style="width: 65px;">
                        Edit
                    </th>
                    <th>
                        Name
                    </th>
                    <th style="width: 65px;">
                        Delete
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var language in Model.Languages)
                {
                    <tr>
                        <td>
                            <a href="@Url.Action("ManageLanguageResourceValues", new { languageId = language.Id })" class="btn-mvc">
                                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                            </a>
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => language.Name)
                        </td>
                        <td>
                            @if (!language.IsDefault)
                            {
                                <a href="@Url.Action("DeleteLanguageConfirmation", new { id = language.Id })" class="btn-mvc">
                                    <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                                </a>
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>

    </div>
</div>

WebMvc.Web/Areas/Admin/Views/AdminLanguage/ImportExport.cshtml
@{
    ViewBag.Title = "Languages";
}
@Html.Partial("_LanguageOptions")
@Html.Action("Languages", "ImportExport")

WebMvc.Web/Areas/Admin/Views/AdminLanguage/Index.cshtml
@{
    ViewBag.Title = "Languages";
}
@Html.Partial("_LanguageOptions")
@Html.Action("GetLanguages")

WebMvc.Web/Areas/Admin/Views/AdminLanguage/ListKeys.cshtml
@using WebMvc.Domain.Constants
@using WebMvc.Web.Application
@model WebMvc.Web.Areas.Admin.ViewModels.ResourceKeyListViewModel
@{
    ViewBag.Title = "All Resource Keys";
}

@Html.Partial("_LanguageOptions")

<div class="panel">
    <div class="panel-heading">
        <h5>@ViewBag.Title</h5>
    </div>
    <div class="panel-content">
        @using (Html.BeginForm("ManageResourceKeys", "AdminLanguage", FormMethod.Post))
        {
            @Html.ValidationSummary(false)
            @Html.AntiForgeryToken()
            @Html.HiddenFor(x => x.PageIndex)
            <div class="input-group tablesearch">
                @Html.TextBoxFor(x => Model.Search, new { @class = "form-control" })
                <span class="input-group-btn">
                    <button class="btn btn-default" type="submit">Search</button>
                </span>
            </div>
        }

        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th style="width: 65px;">
                        Edit
                    </th>
                    <th>
                        Resource Key
                    </th>
                    <th style="width: 65px;">
                        Delete
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var resource in Model.ResourceKeys)
                {

                    <tr>
                        <td class="languageresourcecell">
                            <span class="editresourcekey">
                                <a href="#" class="btn-mvc">
                                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                                </a>
                            </span>
                            <span class="saveresourcekey" style="display: none;">
                                <a href="#" class="btn-mvc">
                                    <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
                                </a>
                            </span>
                        </td>
                        <td class="resourcekeyvalue">
                            <strong>
                                <span class="resourcekeyvaluedisplay">
                                    @Html.DisplayFor(modelItem => resource.Name)
                                </span>
                                <span class="resourcekeyvalueedit form-group" style="display: none;">
                                    <input data-resourcekeyid="@resource.Id" data-oldvalue="@resource.Name" type="text" id="@resource.Id" value="@resource.Name" class="resourcekeyinput form-control" />
                                </span>
                            </strong>
                        </td>
                        <td>
                            <a href="@Url.Action("DeleteResourceConfirmation", new { resourceKeyId = resource.Id })" class="btn-mvc">
                                <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>

        @if (Model.TotalPages > 1)
        {
            @Html.Pager(Convert.ToInt32(Model.PageIndex), SiteConstants.Instance.AdminListPageSize, Convert.ToInt32(Model.TotalCount), new { search = Model.Search })
        }

    </div>
</div>

WebMvc.Web/Areas/Admin/Views/AdminLanguage/ListValues.cshtml
@using WebMvc.Domain.Constants
@using WebMvc.Web.Application
@model WebMvc.Web.Areas.Admin.ViewModels.LanguageListResourcesViewModel
@{
    ViewBag.Title = string.Concat("Resources for ", Model.LanguageName);
}
@Html.Partial("_LanguageOptions")

<div class="panel">
    <div class="panel-heading">
        <h5>@ViewBag.Title</h5>
    </div>
    <div class="panel-content">
        @using (Html.BeginForm("ManageLanguageResourceValues", "AdminLanguage", FormMethod.Post))
        {
            <div class="input-group tablesearch">
                @Html.TextBoxFor(x => Model.Search, new { @class = "form-control" })
                <span class="input-group-btn">
                    <button class="btn btn-default" type="submit">Search Values</button>
                </span>
            </div>
            @Html.HiddenFor(x => x.PageIndex)
            @Html.HiddenFor(x => x.LanguageId)
        }
        @using (Html.BeginForm("ManageLanguageResourceKeys", "AdminLanguage", FormMethod.Post))
        {
            <div class="input-group tablesearch">
                @Html.TextBoxFor(x => Model.Search, new { @class = "form-control" })
                <span class="input-group-btn">
                    <button class="btn btn-default" type="submit">Search Keys</button>
                </span>
            </div>
            @Html.HiddenFor(x => x.PageIndex)
            @Html.HiddenFor(x => x.LanguageId)
        }
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th style="width: 65px;">
                        Edit
                    </th>
                    <th style="width: 180px;">
                        Resource Name
                    </th>
                    <th style="width: auto;">
                        Resource value
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var resource in Model.LocaleResources)
    {
            <tr>
                <td class="languageresourcecell">
                    <span class="editresource">
                        <a href="#" class="btn-mvc">
                            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                        </a>
                    </span>
                    <span class="saveresource" style="display: none;">
                        <a href="#" class="btn-mvc">
                            <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
                        </a>
                    </span>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => resource.LocaleResourceKey)
                </td>
                <td class="resourcevalue">
                    <strong>
                        <span class="resourcevaluedisplay">
                            @Html.DisplayFor(modelItem => resource.ResourceValue)
                        </span>
                        <span class="resourcevalueedit form-group" style="display: none;">
                            <textarea data-languageid="@Model.LanguageId" style="width: 100%;"
                                      data-resourcekey="@resource.LocaleResourceKey"
                                      data-oldvalue="@resource.ResourceValue"
                                      id="@resource.ResourceKeyId"
                                      class="resourcevalueinput form-control">@resource.ResourceValue.Trim()</textarea>
                        </span>
                    </strong>
                </td>
            </tr>
}
            </tbody>
        </table>

        @if (Model.TotalPages > 1)
        {
            @Html.Pager(Convert.ToInt32(Model.PageIndex), SiteConstants.Instance.AdminListPageSize, Convert.ToInt32(Model.TotalCount), new { languageId = Model.LanguageId, search = Model.Search })
        }


    </div>
</div>

WebMvc.Web/Areas/Admin/Views/AdminLanguage/_LanguageOptions.cshtml
<div class="topadminsubnav">
    <div class="btn-group">
        @Html.ActionLink("List languages", "Index", "AdminLanguage", new { Area = "Admin" }, new { @class = "btn-mvc-green" })
        @Html.ActionLink("Manage resource keys", "ManageResourceKeys", "AdminLanguage", new { Area = "Admin" }, new { @class = "btn-mvc-green" })
        @Html.ActionLink("Create a new resource key", "AddResourceKey", "AdminLanguage", new { Area = "Admin" }, new { @class = "btn-mvc-green" })
        @Html.ActionLink("Import New Language", "Languages", "ImportExport", new { Area = "Admin" }, new { @class = "btn-mvc-green" })
    </div>
</div>