WebMvc.Web/Areas/Admin/ViewModels/AdminBookingViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebMvc.Domain.Constants;
using WebMvc.Domain.DomainModel.Entities;

namespace WebMvc.Web.Areas.Admin.ViewModels
{
    public class AdminBookingListViewModel
    {
        public List<Booking> ListBooking;
    }

    public class AdminTypeRoomListViewModel
    {
        public List<TypeRoom> ListTypeRoom;
    }

    public class AdminTypeRoomEditViewModel
    {
        [HiddenInput]
        public Guid Id { get; set; }
        public string Name { get; set; }
        public bool IsShow { get; set; }

        [UIHint(AppConstants.EditorType), AllowHtml]
        public string Note { get; set; }
    }
}

WebMvc.Web/Areas/Admin/Controllers/AdminBookingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebMvc.Domain.Constants;
using WebMvc.Domain.DomainModel.Entities;
using WebMvc.Domain.Interfaces.Services;
using WebMvc.Domain.Interfaces.UnitOfWork;
using WebMvc.Web.Application;
using WebMvc.Web.Areas.Admin.ViewModels;

namespace WebMvc.Web.Areas.Admin.Controllers
{
    [Authorize(Roles = AppConstants.AdminRoleName)]
    public class AdminBookingController : BaseAdminController
    {
        private readonly IBookingSevice _bookingSevice;
        private readonly ITypeRoomSevice _typeRoomSevice;

        public AdminBookingController() : base()
        {
            _bookingSevice = ServiceFactory.Get<IBookingSevice>();
            _typeRoomSevice = ServiceFactory.Get<ITypeRoomSevice>();
        }

        public AdminBookingController(ITypeRoomSevice typeRoomSevice,IBookingSevice bookingSevice, ILoggingService loggingService, IUnitOfWorkManager unitOfWorkManager, IMembershipService membershipService, ISettingsService settingsService, ILocalizationService localizationService)
            : base(loggingService, unitOfWorkManager, membershipService, settingsService, localizationService)
        {
            _bookingSevice = bookingSevice;
            _typeRoomSevice = typeRoomSevice;
        }


        // GET: Admin/AdminBooking
        public ActionResult Index()
        {
            AdminBookingListViewModel viewModel = new AdminBookingListViewModel
            {
                ListBooking = _bookingSevice.GetList(10,1)
            };

            return View(viewModel);
        }

        #region delete
        public ActionResult Delete(Guid id)
        {
            var model = _bookingSevice.Get(id);
            if (model == null)
            {
                TempData[AppConstants.MessageViewBagName] = new GenericMessageViewModel
                {
                    Message = "Đơn đặt phòng không tồn tại",
                    MessageType = GenericMessages.warning
                };

                return RedirectToAction("index");
            }

            return View(model);
        }

        [HttpPost]
        [ActionName("Delete")]
        public ActionResult Delete1(Guid id)
        {
            var model = _bookingSevice.Get(id);
            if (model == null)
            {
                TempData[AppConstants.MessageViewBagName] = new GenericMessageViewModel
                {
                    Message = "Đơn đặt phòng không tồn tại",
                    MessageType = GenericMessages.warning
                };

                return RedirectToAction("index");
            }

            using (var unitOfWork = UnitOfWorkManager.NewUnitOfWork())
            {
                try
                {
                    _bookingSevice.Del(model);


                    unitOfWork.Commit();

                    TempData[AppConstants.MessageViewBagName] = new GenericMessageViewModel
                    {
                        Message = "Xóa đơn đặt phòng thành công",
                        MessageType = GenericMessages.success
                    };
                    return RedirectToAction("index");
                }
                catch (Exception ex)
                {
                    LoggingService.Error(ex.Message);
                    unitOfWork.Rollback();

                    TempData[AppConstants.MessageViewBagName] = new GenericMessageViewModel
                    {
                        Message = "Có lỗi xảy ra khi xóa đơn đặt phòng",
                        MessageType = GenericMessages.warning
                    };
                }
            }


            return View(model);
        }
        #endregion

        #region TypeRoom Action
        public ActionResult TypeRoom()
        {
            AdminTypeRoomListViewModel viewModel = new AdminTypeRoomListViewModel
            {
                ListTypeRoom = _typeRoomSevice.GetAll()
            };

            return View(viewModel);
        }

        public ActionResult NewTypeRoom()
        {
            var viewModel = new AdminTypeRoomEditViewModel
            {
                IsShow = true
            };


            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult NewTypeRoom(AdminTypeRoomEditViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                using (var unitOfWork = UnitOfWorkManager.NewUnitOfWork())
                {
                    try
                    {
                        var typeRoom = new TypeRoom
                        {
                            Name = viewModel.Name,
                            IsShow = viewModel.IsShow,
                            Note = viewModel.Note
                        };

                        _typeRoomSevice.Add(typeRoom);

                        // We use temp data because we are doing a redirect
                        TempData[AppConstants.MessageViewBagName] = new GenericMessageViewModel
                        {
                            Message = "Type Room Created",
                            MessageType = GenericMessages.success
                        };
                        unitOfWork.Commit();

                        return RedirectToAction("TypeRoom");
                    }
                    catch (Exception)
                    {
                        unitOfWork.Rollback();

                        ModelState.AddModelError("", "There was an error creating the Type Room");
                    }
                }
            }
            else
            {
                ModelState.AddModelError("", "There was an error creating the Type Room");
            }
            
            return View(viewModel);
        }

        public ActionResult EditTypeRoom(Guid Id)
        {
            var typeRoom = _typeRoomSevice.Get(Id);
            if (typeRoom == null)
            {
                TempData[AppConstants.MessageViewBagName] = new GenericMessageViewModel
                {
                    Message = LocalizationService.GetResourceString("Errors.NoFindTypeRoom"),
                    MessageType = GenericMessages.warning
                };

                return RedirectToAction("TypeRoom");
            }

            var viewModel = new AdminTypeRoomEditViewModel
            {
                Id = typeRoom.Id,
                Name = typeRoom.Name,
                IsShow = typeRoom.IsShow,
                Note = typeRoom.Note
            };

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditTypeRoom(AdminTypeRoomEditViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                using (var unitOfWork = UnitOfWorkManager.NewUnitOfWork())
                {
                    var typeRoom = _typeRoomSevice.Get(viewModel.Id);
                    if (typeRoom == null)
                    {
                        TempData[AppConstants.MessageViewBagName] = new GenericMessageViewModel
                        {
                            Message = LocalizationService.GetResourceString("Errors.NoFindTypeRoom"),
                            MessageType = GenericMessages.warning
                        };

                        return RedirectToAction("TypeRoom");
                    }

                    typeRoom.Name = viewModel.Name;
                    typeRoom.IsShow = viewModel.IsShow;
                    typeRoom.Note = viewModel.Note;
                    try
                    {
                        _typeRoomSevice.Update(typeRoom);

                        unitOfWork.Commit();
                    }
                    catch (Exception ex)
                    {
                        LoggingService.Error(ex.Message);
                        unitOfWork.Rollback();

                        TempData[AppConstants.MessageViewBagName] = new GenericMessageViewModel
                        {
                            Message = LocalizationService.GetResourceString("Error.TypeRoomEditError"),
                            MessageType = GenericMessages.warning
                        };
                    }
                }
            }

            return View(viewModel);
        }

        #endregion
    }
}

WebMvc.Web/Areas/Admin/Views/AdminBooking/Delete.cshtml
@model WebMvc.Domain.DomainModel.Entities.Booking
@{
    ViewBag.Title = "Xóa đơn đặt phòng";
}
@Html.Partial("_BookingNavButtons")
<div class="panel">
    <div class="panel-heading">
        <h5>@ViewBag.Title</h5>
    </div>
    <div class="panel-content">
        <h2>Xác nhận xóa đơn đặt phòng?</h2>
        <p>Đơn đặt phòng sẽ được xóa hoàn toàn và không thể khôi phục.</p>
        <div class="form-group">
            <input type="text" class="form-control" readonly="readonly" value="@Model.Name" />
        </div>
        @using (Html.BeginForm("Delete", "AdminBooking", FormMethod.Post))
        {
            <div class="submit-holder">
                <input type="submit" class="btn-mvc btn-mvc-large" value="Xác nhận xóa" />
            </div>
        }
    </div>
</div>

WebMvc.Web/Areas/Admin/Views/AdminBooking/EditTypeRoom.cshtml
@model WebMvc.Web.Areas.Admin.ViewModels.AdminTypeRoomEditViewModel

@{
    ViewBag.Title = "Edit Type Room";
}

@Html.Partial("_BookingNavButtons")

<div class="panel">
    <div class="panel-heading">
        <h5>@ViewBag.Title</h5>
    </div>
    <div class="panel-content">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            @Html.ValidationSummary(false)
            @Html.HiddenFor(model => model.Id)
            <div class="form-horizontal">
                @Html.Partial("_FieldsCreateEditTypeRoom", Model)

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" class="btn-mvc-green btn-mvc-large" value="Update" />
                        <a href="@Url.Action("DeleteTypeRoomConfirmation", new { id = Model.Id })" class="btn-mvc btn-mvc-large" role="button">Delete</a>
                    </div>
                </div>
            </div>
        }

    </div>
</div>

WebMvc.Web/Areas/Admin/Views/AdminBooking/Index.cshtml
@model WebMvc.Web.Areas.Admin.ViewModels.AdminBookingListViewModel
@{
    ViewBag.Title = "Booking Manage";
}

@Html.Partial("_BookingNavButtons")


<div class="panel">
    <div class="panel-heading">
        <h5>List Booking</h5>
    </div>
    <div class="panel-content">
        <div id="container">
            <div class="tablescroll">
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th style="width:50px">Edit</th>
                            <th>NamePartner</th>
                            <th style="width:250px">Phone</th>
                            <th style="width:250px">Email</th>
                            <th style="width:250px">CheckIn</th>
                            <th style="width:150px">Create Date</th>
                            <th style="width:50px">Delete</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var it in Model.ListBooking)
                        {
                            <tr>
                                <td>
                                    <span>
                                        <a href="@Url.Action("Edit", new { id = it.Id })" class="btn-mvc">
                                            <span class="glyphicon glyphicon-pencil"></span>
                                        </a>
                                    </span>
                                </td>
                                <td>@it.NamePartner</td>
                                <td>@it.Phone</td>
                                <td>@it.Email</td>
                                <td>@it.CheckIn.ToString("hh:mm dd/MM/yyyy")</td>
                                <td>@it.CreateDate.ToString("hh:mm dd/MM/yyyy")</td>
                                <td>
                                    <a href="@Url.Action("Delete", new { id = it.Id })" class="btn-mvc">
                                        <span class="glyphicon glyphicon-remove"></span>
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

WebMvc.Web/Areas/Admin/Views/AdminBooking/NewTypeRoom.cshtml
@model WebMvc.Web.Areas.Admin.ViewModels.AdminTypeRoomEditViewModel

@{
    ViewBag.Title = "Create Type Room";
}

@Html.Partial("_BookingNavButtons")

<div class="panel">
    <div class="panel-heading">
        <h5>@ViewBag.Title</h5>
    </div>
    <div class="panel-content">
        @using (Html.BeginForm())
        {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    @Html.Partial("_FieldsCreateEditTypeRoom", Model)

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Create" class="btn-mvc-green btn-mvc-large" />
                        </div>
                    </div>
                </div>
        }
    </div>
</div>

WebMvc.Web/Areas/Admin/Views/AdminBooking/TypeRoom.cshtml
@model WebMvc.Web.Areas.Admin.ViewModels.AdminTypeRoomListViewModel
@{
    ViewBag.Title = "Type Room Manage";
}

@Html.Partial("_BookingNavButtons")


<div class="panel">
    <div class="panel-heading">
        <h5>List Booking</h5>
    </div>
    <div class="panel-content">
        <div id="container">
            <div class="tablescroll">
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th style="width:50px">Edit</th>
                            <th style="width:50px">IsShow</th>
                            <th>Name</th>
                            <th style="width:150px">Create Date</th>
                            <th style="width:50px">Delete</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var it in Model.ListTypeRoom)
                        {
                            <tr>
                                <td>
                                    <span>
                                        <a href="@Url.Action("EditTypeRoom", new { id = it.Id })" class="btn-mvc">
                                            <span class="glyphicon glyphicon-pencil"></span>
                                        </a>
                                    </span>
                                </td>
                                <td>@it.IsShow</td>
                                <td>@it.Name</td>
                                <td>@it.CreateDate.ToString("hh:mm dd/MM/yyyy")</td>
                                <td>
                                    <a href="@Url.Action("Delete", new { id = it.Id })" class="btn-mvc">
                                        <span class="glyphicon glyphicon-remove"></span>
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

WebMvc.Web/Areas/Admin/Views/AdminBooking/_BookingNavButtons.cshtml
<div class="topadminsubnav">
    <div class="btn-group" role="group">
        <a href="@Url.Action("Index")" role="button" class="btn-mvc-green">Manage Booking</a>
        <a href="@Url.Action("TypeRoom")" role="button" class="btn-mvc-green">Manage Type Room</a>
        <a href="@Url.Action("NewTypeRoom")" role="button" class="btn-mvc-green">Create Type Room</a>
    </div>
</div>

WebMvc.Web/Areas/Admin/Views/AdminBooking/_FieldsCreateEditTypeRoom.cshtml
@model WebMvc.Web.Areas.Admin.ViewModels.AdminTypeRoomEditViewModel

<div class="form-group">
    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.IsShow, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.CheckBoxFor(model => model.IsShow, new { @class = "form-control" } )
        @Html.ValidationMessageFor(model => model.IsShow, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.Note, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.TextAreaFor(model => model.Note, new { @class = "form-control", @style = "resize:vertical" })
        @Html.ValidationMessageFor(model => model.Note, "", new { @class = "text-danger" })
    </div>
    <script>
        CKEDITOR.replace("Note");
    </script>
</div>